apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-demo-jenkins
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jduimovich0/bootstrap:jenkins-47135eb16ca182ebf8b75ddc437e14defd789f75
          name: container-image
